Repository CSC480-18S/Red-Team, pull requests merged in 2018-04, with the labels that each got.

#162 added stat screen assets from Hannah
  Server Frontend/core/assets/StatsAssets/Gold Team/Gold Average Score.png
  Server Frontend/core/assets/StatsAssets/Gold Team/Gold Bonuses.png
  Server Frontend/core/assets/StatsAssets/Gold Team/Gold Cumulative Score.png
  Server Frontend/core/assets/StatsAssets/Gold Team/Gold Dirty Words.png
  Server Frontend/core/assets/StatsAssets/Gold Team/Gold FP Words.png
  Server Frontend/core/assets/StatsAssets/Gold Team/Gold Game Score.png
  Server Frontend/core/assets/StatsAssets/Gold Team/Gold Heading.png
  Server Frontend/core/assets/StatsAssets/Gold Team/Gold Highest Word Score.png
  Server Frontend/core/assets/StatsAssets/Gold Team/Gold Longest Word.png
  Server Frontend/core/assets/StatsAssets/Gold Team/Gold Oswego Words.png
  Server Frontend/core/assets/StatsAssets/Gold Team/Gold Team Container.png
  Server Frontend/core/assets/StatsAssets/Gold Team/Gold Top Players.png
  Server Frontend/core/assets/StatsAssets/Green Team/Green Average Score.png
  Server Frontend/core/assets/StatsAssets/Green Team/Green Bonuses.png
  Server Frontend/core/assets/StatsAssets/Green Team/Green Cumulative Score.png
  Server Frontend/core/assets/StatsAssets/Green Team/Green Dirty Words.png
  Server Frontend/core/assets/StatsAssets/Green Team/Green FP Words.png
  Server Frontend/core/assets/StatsAssets/Green Team/Green Game Score.png
  Server Frontend/core/assets/StatsAssets/Green Team/Green Heading.png
  Server Frontend/core/assets/StatsAssets/Green Team/Green Highest Word Score.png
  Server Frontend/core/assets/StatsAssets/Green Team/Green Longest Word.png
  Server Frontend/core/assets/StatsAssets/Green Team/Green Oswego Words.png
  Server Frontend/core/assets/StatsAssets/Green Team/Green Team Container.png
  Server Frontend/core/assets/StatsAssets/Green Team/Green Top Players.png
  Server Frontend/core/assets/StatsAssets/MainScreen.png
  Server Frontend/core/assets/StatsAssets/Player Stats/Most Frequent Players.png
  Server Frontend/core/assets/StatsAssets/Player Stats/Oswebble Logo_.png
  Server Frontend/core/assets/StatsAssets/Player Stats/Overall Frequently Played.png
  Server Frontend/core/assets/StatsAssets/Player Stats/Player Dirty Word.png
  Server Frontend/core/assets/StatsAssets/Player Stats/Player Highest Game Score.png
  Server Frontend/core/assets/StatsAssets/Player Stats/Player Longest Word.png
  Server Frontend/core/assets/StatsAssets/Player Stats/Players Highest Word Score.png
  Server Frontend/core/assets/StatsAssets/Player Stats/Top Overall Players.png
  Server Frontend/core/assets/StatsAssets/T-Test Sentence.png
Labels: Priority: Low, Type: Feature, review

#164 misc fixes
  Server Backend/entities/ServerManager.js
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/HandActor.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/InfoPanelActor.java
  Server Frontend/core/src/com/csc480/game/GUI/GameScreen.java
Labels: Priority: Medium, Type: Maintenance, review

#165 Sdem
  Server Backend/entities/PlayerManager.js
  Server Backend/entities/ServerManager.js
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/Board.java
Labels: Priority: Medium, Type: Enhancement, review

#166 AI plays forever
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/Board.java
  Server Frontend/core/src/com/csc480/game/Engine/WordVerification.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/GameBoardTable.java
Labels: Priority: Medium, Type: Enhancement, review

#167 fix
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
Labels: Priority: Medium, review

#171 bruh
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/Board.java
  Server Frontend/core/src/com/csc480/game/Engine/WordVerification.java
Labels: Priority: Medium, Type: Bug, Type: Maintenance, review

#158 specification tests for GameDB and Dictionary applications
  .gitignore
  Database/Dictionary/src/test/java/com/csc480red/dictionary/DictionaryApplicationTests.java
  Database/Dictionary/src/test/resources/badwords.txt
  Database/Dictionary/src/test/resources/invalidwords.txt
  Database/Dictionary/src/test/resources/specialwords.txt
  Database/Dictionary/src/test/resources/validwords.txt
  Database/GameDB/src/test/java/com/csc480red/gamedb/GameDbApplicationTests.java
  Database/GameDB/src/test/java/com/csc480red/gamedb/PlayerTests.java
  Database/GameDB/src/test/java/com/csc480red/gamedb/TeamTests.java
Labels: Priority: Low, Type: Maintenance, review

#168 Use axios to get tested initial tile info from the server side; imple…
  Frontend/index.html
  Frontend/initial_tile.json
  Frontend/models/game-board-model.js
  Frontend/refill.json
  Frontend/view-models/game-board-view-model.js
  Frontend/views/styles.css
Labels: Priority: Low, Type: Enhancement, Type: Feature, review

#175 fixes
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/WordVerification.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/HandActor.java
Labels: review

#181 Display socket data
  Frontend/models/game-board-model.js
Labels: Priority: Low, Type: Maintenance

#182 null is now really null
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
Labels: (ノಠ益ಠ)ノ彡┻━┻, review

#185 resize fix
  Server Frontend/core/src/com/csc480/game/GUI/Actors/GameBoardTable.java
Labels: review

#186 most recent
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
Labels: (ノಠ益ಠ)ノ彡┻━┻, Priority: High, Type: Maintenance, review

#189 Full communication with engine
  Frontend/models/game-board-model.js
Labels: Priority: High, Type: Feature, Type: Maintenance

#190 Mmmmmmmmmfixes
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/Board.java
  Server Frontend/core/src/test/java/com/csc480/game/Engine/BoardTest.java
  Server Frontend/core/src/test/java/com/csc480/game/Engine/WordVerificationTest.java
Labels: Priority: Medium, Type: Documentation, Type: Maintenance, review

#191 Found the missing Docs
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/Board.java
  Server Frontend/core/src/com/csc480/game/Engine/WordVerification.java
Labels: (ノಠ益ಠ)ノ彡┻━┻, Priority: Low, Type: Documentation, review

#192 Socket fixes
  Frontend/models/game-board-model.js
Labels: Priority: Medium, Type: Feature, Type: Maintenance

#195 debug messages and AI wait
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/test/java/com/csc480/game/Engine/BoardTest.java
Labels: (ノಠ益ಠ)ノ彡┻━┻, Priority: High, Type: Documentation, review

#197 Mmmmmmmmmfixes
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/WordVerification.java
Labels: Priority: Medium, Type: Feature, Type: Maintenance, review

#202 all players updating state
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/InfoPanelActor.java
Labels: Priority: High, Type: Enhancement, review

#206 Removed AI for the demo
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
Labels: Priority: Medium, review

#211 Socket fixes
  Frontend/models/game-board-model.js
Labels: Priority: Medium, Type: Enhancement, Type: Feature

#215 gui update
  Server Frontend/core/assets/tilesAtlas.atlas
  Server Frontend/core/assets/tilesAtlas.png
  Server Frontend/core/assets/tilesAtlas2.png
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/TextureManager.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/GameBoardTable.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/HandActor.java
  Server Frontend/core/src/com/csc480/game/GUI/GameScreen.java
Labels: review

#217 added dummy playWord, AI now start from different indexes when search…
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/TestingInputProcessor.java
Labels: (ノಠ益ಠ)ノ彡┻━┻, Priority: High, Status: Revision Needed, Type: Enhancement, review

#218 Gui update
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/desktop/src/com/csc480/game/desktop/DesktopLauncher.java
Labels: Type: Enhancement, Type: Feature

#222 Fixed bug
  Server Backend/entities/Gameboard.js
Labels: Priority: High, Type: Maintenance, review

#219 Added the tables to the StatsScreen create and render. Created font m…
  Server Frontend/core/assets/StatsAssets/statsBackground.png
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/FontManager.java
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/Hud.java
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/StatsTables.java
  Server Frontend/core/src/com/csc480/stats/GUI/StatsScreen.java
Labels: review

#223 cleaning up and refactoring
  Server Backend/entities/Bag.js
  Server Backend/entities/GameManager.js
  Server Backend/entities/ServerManager.js
  Server Backend/helpers/Debug.js
  Server Backend/helpers/Extractor.js
  Server Backend/helpers/Override.js
  Server Backend/helpers/ResponseHandler.js
  Server Backend/helpers/ScoreCalculator.js
  Server Backend/helpers/Socket.js
  Server Backend/helpers/VerifyTokens.js
Labels: Priority: Medium, Type: Feature, Type: Maintenance, review

#224 added removeAI event
  Server Backend/entities/FrontendManager.js
  Server Backend/entities/ServerManager.js
Labels: Priority: Medium, Type: Enhancement, Type: Feature, review

#225 fix
  Server Backend/entities/ServerManager.js
Labels: Priority: Low, Type: Maintenance, review

#229 Updates
  Server Backend/entities/GameManager.js
  Server Backend/entities/PlayerManager.js
  Server Backend/helpers/Extractor.js
  Server Backend/helpers/LetterDistributor.js
  Server Backend/helpers/ResponseHandler.js
  Server Backend/package.json
  Server Backend/static/frontend_board_model.js
  Server Backend/static/frontend_board_view_model.js
Labels: Priority: Medium, Type: Enhancement, review

#233 finished stats page
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/Hud.java
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/StatsTables.java
  Server Frontend/core/src/com/csc480/stats/GUI/StatsScreen.java
  Server Frontend/core/src/com/csc480/stats/StatsViewer.java
Labels: review

#235 fixed screen sizing
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/Hud.java
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/StatsTables.java
  Server Frontend/core/src/com/csc480/stats/GUI/StatsScreen.java
Labels: review

#236 Fixed the crash issue when servers aren't running
  Server Frontend/core/src/com/csc480/stats/StatsConnection.java
  Server Frontend/core/src/com/csc480/stats/StatsViewer.java
Labels: Priority: Medium, Type: Bug, review

#237 updated tests files to fix issues
  .travis.yml
  Database/Dictionary/pom.xml
  Database/GameDB/pom.xml
  Server Backend/entities/GameManager.js
  Server Backend/entities/PlayerManager.js
  Server Backend/package.json
  Server Backend/tests/test.js
Labels: Priority: High, Type: Maintenance, review

#240 Prototype stats page
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/FontManager.java
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/Hud.java
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/StatsTables.java
  Server Frontend/core/src/com/csc480/stats/JsonResponse.java
  Server Frontend/core/src/com/csc480/stats/StatsConnection.java
  Server Frontend/core/src/com/csc480/stats/StatsViewer.java
  Server Frontend/core/src/com/csc480/stats/teamData.java
Labels: Priority: Critical, Type: Bug, Type: Enhancement, Type: Feature, review

#241 Update login and register pages
  Server Backend/package.json
  Server Backend/routes/main-route.js
  Server Backend/static/css/login.css
  Server Backend/static/css/register.css
  Server Backend/static/scss/login.scss
  Server Backend/static/scss/register.scss
  Server Backend/views/login.html
  Server Backend/views/register.html
Labels: Priority: Medium, Type: Enhancement, Type: Maintenance, review

#243 Added rules alert for registration page
  Server Backend/views/register.html
Labels: Priority: Low, Type: Enhancement, review

#245 Fix an issue and add more features
  Database/GameDB/src/main/java/com/csc480red/gamedb/PlayedWord.java
  Database/GameDB/src/main/java/com/csc480red/gamedb/Player.java
  Database/GameDB/src/main/java/com/csc480red/gamedb/Team.java
  Database/GameDB/src/main/java/com/csc480red/gamedb/WordFrequency.java
Labels: Priority: Medium, Type: Enhancement

#246 TeamData name change, still broken
  Server Frontend/core/src/com/csc480/stats/TeamData.java
Labels: review

#248 fixes for demo
  Server Frontend/core/assets/Background.jpg
  Server Frontend/core/assets/board.png
  Server Frontend/core/assets/tilesAtlas.atlas
  Server Frontend/core/assets/tilesAtlas.png
  Server Frontend/core/assets/tilesAtlas2.png
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/TestingInputProcessor.java
  Server Frontend/core/src/com/csc480/game/Engine/TextureManager.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/GameOverActor.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/InfoPanelActor.java
  Server Frontend/core/src/com/csc480/game/GUI/GameScreen.java
  Server Frontend/desktop/src/com/csc480/game/desktop/DesktopLauncher.java
Labels: Priority: Medium, Type: Enhancement, review

#247 Set fonts to b-sans; stop providing the function of moving a selected…
  Server Backend/static/css/frontend_play_area.css
  Server Backend/static/js/frontend_board_model.js
  Server Backend/views/gameboard.html
Labels: Priority: Medium, Type: Enhancement, review

#253 Fixed the issue: can't play tiles after a play
  Server Backend/static/js/frontend_board_model.js
Labels: Priority: Medium, Type: Enhancement

#259 changed to new skin and readjusted tables to fit new font
  Server Frontend/core/assets/skin/BorderedRectangle.png
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/FontManager.java
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/Hud.java
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/StatsTables.java
Labels: review

#261 change skin and adjusted sizing and positions..again..
  Server Frontend/core/assets/skin/BorderedRectangle.png
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/FontManager.java
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/Hud.java
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/StatsTables.java
Labels: review

#258 added new logo
  Server Backend/static/imgs/logo-min.png
Labels: Priority: Low, Type: Enhancement

#257 AI calculation timeout
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
Labels: Priority: Low, Type: Feature, review

#262 Added button icons, changed button color and screen background color
  Server Backend/static/css/frontend_play_area.css
  Server Backend/static/imgs/done.svg
  Server Backend/static/imgs/exchange.png
  Server Backend/static/imgs/shuffle.png
  Server Backend/static/js/frontend_board_model.js
  Server Backend/views/gameboard.html
Labels: Priority: Medium, Type: Maintenance

#263 Finished JSON parsing
  Server Frontend/core/src/com/csc480/stats/StatsAdapter.java
  Server Frontend/core/src/com/csc480/stats/StatsConnection.java
  Server Frontend/core/src/com/csc480/stats/StatsViewer.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/JsonResponse.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/JsonResponse2.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/JsonResponse3.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/JsonResponse4.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/JsonResponse5.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/Metadata.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/NestedData.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/NestedData2.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/NestedData3.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/Player.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/PlayerData.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/Score.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/ScoreData.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/TeamData.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/Word.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/WordData.java
  Server Frontend/core/src/com/csc480/stats/jsonObjects/Words.java
Labels: Priority: Critical, Type: Bug, Type: Feature, review

#267 Implemented T-test
  Server Frontend/core/src/com/csc480/stats/StatsConnection.java
  Server Frontend/core/src/com/csc480/stats/StatsViewer.java
Labels: Priority: Medium, Type: Feature, review

#269 if conditional fixes
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/Hud.java
Labels: Priority: Critical, Type: Bug, review

#271 updated front-end
  Server Backend/static/css/frontend_play_area.css
  Server Backend/static/js/frontend_board_model.js
  Server Backend/views/gameboard.html
Labels: Priority: Low, Type: Enhancement, Type: Maintenance

#270 Db integration
  Database/Dictionary/pom.xml
  Database/GameDB/pom.xml
  Database/GameDB/src/main/java/com/csc480red/gamedb/PlayerRepository.java
  Server Backend/config.js
  Server Backend/entities/GameManager.js
  Server Backend/entities/Gameboard.js
  Server Backend/entities/PlayerManager.js
  Server Backend/helpers/DB.js
  Server Backend/helpers/FileManager.js
  Server Backend/helpers/Logger.js
  Server Backend/helpers/MacGrabber.js
  Server Backend/helpers/RedundancyManager.js
  Server Backend/helpers/ResponseHandler.js
  Server Backend/helpers/ScoreCalculator.js
  Server Backend/helpers/VerifyTokens.js
  Server Backend/package.json
  Server Backend/routes/main-route.js
  Server Backend/routes/users-route.js
  Server Backend/server.js
  Server Backend/static/css/frontend_play_area.css
  Server Backend/static/css/login.css
  Server Backend/static/css/register.css
  Server Backend/static/imgs/logo-min.png
  Server Backend/static/imgs/logo.png
  Server Backend/static/js/frontend_board_model.js
  Server Backend/static/scss/frontend_play_area.scss
  Server Backend/static/scss/login.scss
  Server Backend/static/scss/register.scss
  Server Backend/views/gameboard.html
  Server Backend/views/login.html
  Server Backend/views/register.html
  Server Frontend/core/src/test/java/com/csc480/game/Engine/BoardTest.java
  Server Frontend/core/src/test/java/com/csc480/game/Engine/WordVerificationTest.java
  build.bat
Labels: Priority: High, Status: Work in Progress, Type: Feature, Type: Maintenance, review

#279 fixed memory leak, fixed AI trying to cheat
  Server Frontend/core/assets/Background.jpg
  Server Frontend/core/assets/BoardTilemap.tmx
  Server Frontend/core/assets/BoardTileset.tsx
  Server Frontend/core/assets/POCboardTiles.png
  Server Frontend/core/assets/board.png
  Server Frontend/core/assets/data/words.txt
  Server Frontend/core/assets/goldBar.png
  Server Frontend/core/assets/greenBar.png
  Server Frontend/core/assets/identifiersHelper.tmx
  Server Frontend/core/assets/images/tilesAtlas.atlas
  Server Frontend/core/assets/images/tilesAtlas.png
  Server Frontend/core/assets/images/tilesAtlas2.png
  Server Frontend/core/assets/images/tilesAtlas3.png
  Server Frontend/core/assets/rack.jpg
  Server Frontend/core/assets/temp.png
  Server Frontend/core/assets/tilesAtlas.png
  Server Frontend/core/assets/tilesAtlas2.png
  Server Frontend/core/assets/tilesAtlas3.png
  Server Frontend/core/assets/tilesAtlas4.png
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/TestingInputProcessor.java
  Server Frontend/core/src/com/csc480/game/Engine/TextureManager.java
  Server Frontend/core/src/com/csc480/game/Engine/WordVerification.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/GameBoardTable.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/HandActor.java
Labels: Priority: Critical, Type: Bug Fix, review

#281 gui crash bug fix
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/WordVerification.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/HandActor.java
  Server Frontend/core/src/com/csc480/game/GUI/GameScreen.java
  buildWINDOWS.bat
Labels: Priority: Critical, Type: Bug Fix, review

#284 AI get reset when frontend reconnects
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
Labels: review

#296 Fixes #282
  Server Backend/helpers/ResponseHandler.js
Labels: Priority: Low, Type: Bug Fix, Type: Maintenance, review

#298 Fixes #297
  Server Backend/views/register.html
Labels: Priority: Low, Type: Enhancement, review

#301 Resolves #295
  Database/Dictionary/src/main/resources/specialwords.txt
Labels: Priority: Low, Type: Enhancement

#300 Fixes #282
  Server Backend/entities/GameManager.js
  Server Backend/entities/PlayerManager.js
Labels: Priority: Low, Type: Enhancement, Type: Maintenance, review

#303 Stats update, fixes #277
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/Hud.java
  Server Frontend/core/src/com/csc480/stats/GUI/StatsScreen.java
Labels: Priority: Medium, Type: Bug Fix, Type: Enhancement, review

#302 Fixes #285
  Server Frontend/build.gradle
  Server Frontend/core/assets/aiwords.txt
  Server Frontend/core/src/com/csc480/game/Engine/WordVerification.java
Labels: Type: Bug Fix, Type: Enhancement, review

#315 References #314 #309
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/TestingInputProcessor.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/GameOverActor.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/HandActor.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/InfoPanelActor.java
  Server Frontend/core/src/com/csc480/game/GUI/GameScreen.java
Labels: Priority: Medium, Type: Bug Fix, review

#317 WebSocket Implemented in Front End Board Model
  Server Backend/static/js/frontend_board_model.js
Labels: Priority: High, Type: Enhancement

#323 fixes #313
  Server Frontend/core/src/com/csc480/stats/GUI/StatsScreen.java
Labels: review

#319 Client displays playTime
  Server Backend/static/js/frontend_board_model.js
Labels: Priority: Low, Type: Bug Fix, review

#332 replaced AI's word list with a smaller 15k
  Server Frontend/core/assets/LtoS15kWordCorpus.txt
  Server Frontend/core/src/com/csc480/game/Engine/WordVerification.java
Labels: review

#312 Label fixes
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/Hud.java
Labels: Priority: Low, Type: Enhancement, review

#338 added smaller background image to gameboard.html
  Server Backend/static/css/frontend_play_area.css
  Server Backend/static/imgs/small3-unsplash.jpg
Labels: Priority: Low, Type: Enhancement
