Repository CSC480-18S/Red-Team, pull requests merged in 2018-03, with the labels that each got.

#99 Updated stats endpoints
  Server Backend/routes/stats-route.js
Labels: Priority: Low, Status: Accepted, Type: Enhancement

#103 GUI Overhaul
  Server Frontend/core/assets/BoardTilemap.tmx
  Server Frontend/core/assets/BoardTileset.tsx
  Server Frontend/core/assets/POCBoard.tmx
  Server Frontend/core/assets/POCBoardTileset.tsx
  Server Frontend/core/assets/POCboardTiles.png
  Server Frontend/core/assets/badlogic.jpg
  Server Frontend/core/assets/identifiersHelper.tmx
  Server Frontend/core/assets/rack.jpg
  Server Frontend/core/assets/spriteAtlas.atlas
  Server Frontend/core/assets/spriteAtlas.png
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/Board.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/Player.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/TileData.java
  Server Frontend/core/src/com/csc480/game/Engine/TestingPOCScreen.java
  Server Frontend/core/src/com/csc480/game/Engine/TextureManager.java
  Server Frontend/core/src/com/csc480/game/Engine/TiledUtils.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/GameBoardActor.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/HandActor.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/TileActor.java
  Server Frontend/core/src/com/csc480/game/GUI/GameScreen.java
  Server Frontend/core/src/com/csc480/game/GameAdapter.java
  Server Frontend/core/src/com/csc480/game/OswebbleGame.java
  Server Frontend/desktop/src/com/csc480/game/desktop/DesktopLauncher.java
Labels: Priority: Critical, Type: Documentation, Type: Feature

#105 Add the ability to search players by username
  Database/GameDB/src/main/java/com/csc480red/gamedb/PlayerRepository.java
Labels: Priority: Medium, Type: Feature

#107 Implemented player stats endpoint
  Server Backend/routes/stats-route.js
Labels: Priority: Low, Status: Accepted, Type: Enhancement, Type: Maintenance

#101 Enhancements
  Server Backend/entities/Gameboard.js
  Server Backend/entities/Tile.js
  Server Backend/helpers/Gameboard.js
  Server Backend/package-lock.json
  Server Backend/package.json
  Server Backend/routes/game-route.js
  Server Backend/tests/test.js
Labels: Priority: Medium, Status: Work in Progress, Type: Enhancement, Type: Feature, review

#117 Implemented team stats endpoint
  Server Backend/routes/stats-route.js
Labels: Type: Feature, Type: Sprint Task

#122 updated to work with dictionary database
  .travis.yml
Labels: Priority: Medium, Type: Maintenance, review

#127 Fix the game board shrinking problem when placing tiles; Expand 1-step undo feature to every tile
  Frontend/index.html
  Frontend/models/game-board-model.js
  Frontend/view-models/game-board-view-model.js
  Frontend/views/styles.css
Labels: Priority: Medium, Type: Enhancement, review

#129 Added POC AI
  Server Frontend/build.gradle
  Server Frontend/core/assets/BoardTilemap.tmx
  Server Frontend/core/assets/BoardTileset.tsx
  Server Frontend/core/assets/POCboardTiles.png
  Server Frontend/core/assets/badlogic.jpg
  Server Frontend/core/assets/identifiersHelper.tmx
  Server Frontend/core/assets/rack.jpg
  Server Frontend/core/assets/words.txt
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/Board.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/Placement.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/Player.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/TileData.java
  Server Frontend/core/src/com/csc480/game/Engine/SocketManager.java
  Server Frontend/core/src/com/csc480/game/Engine/TestingInputProcessor.java
  Server Frontend/core/src/com/csc480/game/Engine/TextureManager.java
  Server Frontend/core/src/com/csc480/game/Engine/TiledUtils.java
  Server Frontend/core/src/com/csc480/game/Engine/WordVerification.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/GameBoardActor.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/HandActor.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/TileActor.java
  Server Frontend/core/src/com/csc480/game/GUI/GameScreen.java
  Server Frontend/core/src/com/csc480/game/GameAdapter.java
  Server Frontend/core/src/com/csc480/game/OswebbleGame.java
  Server Frontend/core/src/test/java/com/csc480/game/Engine/Model/BoardTest.java
  Server Frontend/core/src/test/java/com/csc480/game/Engine/WordVerificationTest.java
  Server Frontend/desktop/src/com/csc480/game/desktop/DesktopLauncher.java
Labels: Priority: Medium, review

#134 ai-fixes
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/TestingInputProcessor.java
  Server Frontend/core/src/com/csc480/game/Engine/TiledUtils.java
  Server Frontend/core/src/com/csc480/game/Engine/WordVerification.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/GameBoardActor.java
  Server Frontend/core/src/test/java/com/csc480/game/Engine/WordVerificationTest.java
Labels: review

#137 fixed sockets not existing error
  Server Backend/helpers/Socket.js
  Server Backend/server.js
Labels: Priority: High, review

#139 fixed bug
  Server Backend/routes/users-route.js
Labels: Priority: High, review

#135 Initialize tiles based on data
  Frontend/index.html
  Frontend/models/game-board-model.js
  Frontend/view-models/game-board-view-model.js
  Frontend/views/styles.css
Labels: Priority: Low, Type: Enhancement, review

#145 GM fixes, Frontend Integration
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/Player.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/TileData.java
  Server Frontend/core/src/com/csc480/game/Engine/SocketManager.java
  Server Frontend/core/src/com/csc480/game/Engine/TestingInputProcessor.java
  Server Frontend/core/src/com/csc480/game/Engine/WordVerification.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/HandActor.java
  Server Frontend/core/src/com/csc480/game/GUI/GameScreen.java
  Server Frontend/core/src/com/csc480/game/GameAdapter.java
  Server Frontend/core/src/com/csc480/game/OswebbleGame.java
Labels: Priority: High, Type: Feature, Type: Sprint Task, review

#146 updated tileData to reflect backend
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/Board.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/TileData.java
Labels: review

#149 Frontend Socket start of implementation
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
Labels: review

#150 more GM updates
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/SocketManager.java
Labels: review

#151 Tested sockets, updated GM sockets, added InfoPlanelActor
  Server Backend/package-lock.json
  Server Frontend/core/assets/Background.jpg
  Server Frontend/core/assets/skin/exempleSkin.atlas
  Server Frontend/core/assets/skin/exempleSkin.json
  Server Frontend/core/assets/skin/exempleSkin.png
  Server Frontend/core/assets/skin/font-export.fnt
  Server Frontend/core/assets/skin/font-title-export.fnt
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/SocketManager.java
  Server Frontend/core/src/com/csc480/game/Engine/TextureManager.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/InfoPanelActor.java
  Server Frontend/core/src/com/csc480/game/GUI/GameScreen.java
Labels: review

#155 Some socket events added to AI
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
Labels: Priority: Medium, Type: Feature, Type: Maintenance, review

#156 gameboard fixes
  Server Frontend/core/assets/tilesAtlas.atlas
  Server Frontend/core/assets/tilesAtlas.png
  Server Frontend/core/assets/tilesAtlas2.png
  Server Frontend/core/assets/tilesAtlas3.png
  Server Frontend/core/assets/tilesAtlas4.png
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/TestingInputProcessor.java
  Server Frontend/core/src/com/csc480/game/Engine/TextureManager.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/GameBoardTable.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/HandActor.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/InfoPanelActor.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/TileActor.java
  Server Frontend/core/src/com/csc480/game/GUI/GameScreen.java
Labels: (ノಠ益ಠ)ノ彡┻━┻, Priority: Medium, Type: Enhancement, Type: Feature, review

#160 fixed updating players
  Server Frontend/core/src/com/csc480/game/Engine/GameManager.java
  Server Frontend/core/src/com/csc480/game/Engine/Model/AI.java
  Server Frontend/core/src/com/csc480/game/Engine/TestingInputProcessor.java
  Server Frontend/core/src/com/csc480/game/Engine/TextureManager.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/GameBoardTable.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/HandActor.java
  Server Frontend/core/src/com/csc480/game/GUI/Actors/InfoPanelActor.java
  Server Frontend/core/src/com/csc480/game/GUI/GameScreen.java
  Server Frontend/desktop/build.gradle
Labels: Priority: Medium, Type: Enhancement, Type: Sprint Task, review
