Repository CSC480-18S/Red-Team, pull requests merged in 2018-02, with the labels that each got.

#36 Add README.md and LICENSE
  Database/Dictionary/README.md
Labels: Priority: Low, Type: Maintenance

#40 Added boilerplate files and structure
  Server Backend/.gitignore
  Server Backend/README.md
  Server Backend/package-lock.json
  Server Backend/package.json
  Server Backend/routes/game-route.js
  Server Backend/routes/index-route.js
  Server Backend/routes/stats-route.js
  Server Backend/routes/users-route.js
  Server Backend/server.js
Labels: Type: Maintenance, review

#41 Renamed
  Assets/Concepts/Concept Set #2/Desktop-Laptop/1_WF_FrontPage.jpg
  Assets/Concepts/Concept Set #2/Desktop-Laptop/2_WF_FrontPage_2.jpg
  Assets/Concepts/Concept Set #2/Desktop-Laptop/3_WF_SignUpPage.jpg
  Assets/Concepts/Concept Set #2/Desktop-Laptop/4_WF_Gameboard.jpg
  Assets/Concepts/Concept Set #2/Desktop-Laptop/5_WF_Gameboard_2.jpg
  Assets/Concepts/Concept Set #2/Desktop-Laptop/6_WF_Gameboard_3.jpg
  Assets/Concepts/Concept Set #2/Desktop-Laptop/6_WF_Gameboard_3.psd
Labels: (ノಠ益ಠ)ノ彡┻━┻, Priority: Critical, Type: Maintenance, review

#47 added get all users(without merge conflict hopefully)
  Server Backend/routes/users-route.js
Labels: Priority: Low, Type: Feature

#48 added updated tile design
  Assets/Concepts/Concept Set #2/Tiles&Racks_SPRITE.jpg
  Assets/Concepts/Concept Set #2/Tiles&Racks_SPRITE.psd
  Assets/Concepts/Concept Set #2/tilesSprites2.jpg
  Assets/Concepts/Concept Set #2/tilesSprites2.psd
Labels: Type: Enhancement

#50 Added addUser
  Server Backend/routes/users-route.js
Labels: Status: Revision Needed, Type: Feature, review

#51 Added the views folder and html file for user creating text field
  Server Backend/Views Folder/CreateUser.html
  package-lock.json
Labels: Priority: Low, Type: Feature

#52 added addUser.html
  Server Backend/views/addUser.html
Labels: Priority: Low, Type: Feature

#53 Finalizing POC
  Server Backend/Views Folder/CreateUser.html
  Server Backend/routes/users-route.js
  Server Backend/views/allUsers.html
  package-lock.json
Labels: Priority: Medium, Type: Enhancement, Type: Feature, Type: Maintenance, review

#58 Fixes
  Server Backend/views/addUser.html
  Server Backend/views/allUsers.html
Labels: review

#59 fixed splice method, was not removing user
  Server Backend/routes/users-route.js
Labels: Priority: Medium, Type: Bug, Type: Enhancement, review

#64 Broke application into Addapter and Game. Added packages for GUI and …
  Server Frontend/core/src/Csc480.gwt.xml
  Server Frontend/core/src/com/csc480/game/GUI/GameScreen.java
  Server Frontend/core/src/com/csc480/game/GameAdapter.java
  Server Frontend/core/src/com/csc480/game/OswebbleGame.java
  Server Frontend/core/src/com/mygdx/game/MyGdxGame.java
  Server Frontend/desktop/src/com/csc480/game/desktop/DesktopLauncher.java
Labels: Priority: Low, Status: Pending

#66 Stats endpoint stubs with comments
  Server Backend/routes/stats-route.js
Labels: Priority: Medium, Status: Accepted, Type: Documentation, Type: Feature

#68 Added a couple things
  .stickler.yml
  .travis.yml
  README.md
  Server Backend/.eslintrc.json
  Server Backend/Tests/test.js
  Server Backend/helpers/Gameboard.js
  Server Backend/helpers/Tile.js
  Server Backend/package-lock.json
  Server Backend/package.json
  Server Backend/routes/game-route.js
  Server Backend/routes/index-route.js
  Server Backend/routes/stats-route.js
  Server Backend/routes/users-route.js
  Server Backend/server.js
Labels: Priority: Medium, Type: Documentation, Type: Enhancement, Type: Feature, Type: Maintenance, review

#69 added eslint auto fixer
  .stickler.yml
Labels: Priority: High, Type: Maintenance, review

#70 Removed stickler
  .stickler.yml
Labels: Type: Maintenance, review

#67 Added screen tap and 1-step undo features to move tiles
  Frontend/index.html
  Frontend/models/game-board-model.js
  Frontend/view-models/game-board-view-model.js
  Frontend/views/styles.css
Labels: review

#71 Wrote definitions for user endpoints
  Server Backend/routes/users-route.js
Labels: Priority: Low, Status: Accepted

#72 Added tests and methods for Gameboard and Tile classes
  Server Backend/Tests/test.js
  Server Backend/helpers/Gameboard.js
  Server Backend/helpers/Tile.js
  Server Backend/package-lock.json
  Server Backend/package.json
  Server Backend/routes/game-route.js
  Server Backend/views/gameboard.html
Labels: Priority: Low, Type: Feature, review

#78 Maintenance
  .github/PULL_REQUEST_TEMPLATE.md
  Server Backend/package.json
Labels: Priority: Low, Status: Available, Type: Maintenance, review

#76 Finalized Monitor 1 layout
  Frontend/models/Monitor1_FinalLayout.png
Labels: Status: Accepted, Type: Feature, review

#80 Maintenance
  Server Backend/.eslintrc.json
  Server Backend/Tests/test.js
  Server Backend/package-lock.json
  Server Backend/package.json
  Server Backend/tests/setup.js
  Server Backend/tests/test.js
  package-lock.json
Labels: Priority: High, Type: Enhancement, Type: Maintenance, review

#84 Board validation
  Server Backend/helpers/Gameboard.js
  Server Backend/tests/test.js
Labels: Priority: Medium, Type: Enhancement, Type: Feature, review

#85 Added documentation, hashmap for word validation,and a basic socket manager template.
  Server Frontend/build.gradle
  Server Frontend/core/assets/words.txt
  Server Frontend/core/src/com/csc480/game/Engine/Board.java
  Server Frontend/core/src/com/csc480/game/Engine/Placement.java
  Server Frontend/core/src/com/csc480/game/Engine/SocketManager.java
  Server Frontend/core/src/com/csc480/game/Engine/TestingInputProcessor.java
  Server Frontend/core/src/com/csc480/game/Engine/TestingPOCScreen.java
  Server Frontend/core/src/com/csc480/game/Engine/TileData.java
  Server Frontend/core/src/com/csc480/game/Engine/WordVerification.java
  Server Frontend/desktop/src/com/csc480/game/desktop/DesktopLauncher.java
Labels: Priority: Medium, Type: Documentation, Type: Feature

#86 New stats endpoints
  Server Backend/routes/stats-route.js
Labels: review

#88 Json standardization
  Server Backend/helpers/Override.js
  Server Backend/server.js
Labels: Priority: High, Status: On Hold, Type: Feature, review

#97 updated for java tests
  .travis.yml
  Database/BadWordDictionary/mvnw
Labels: Priority: High, review
