Repository CSC480-18S/Red-Team, pull requests merged in 2018-05, with the labels that each got.

#333 Mobile Client Sends "Swap" Event to Backend
  Server Backend/static/js/frontend_board_model.js
  Server Frontend/build.gradle
Labels: Priority: High, Type: Bug Fix, Type: Maintenance, review

#321 Fixes #306
  Server Backend/static/js/frontend_board_model.js
Labels: Priority: Low, Type: Bug Fix, review

#343 compressed background file
  Server Frontend/core/assets/Background 2.png
  Server Frontend/core/assets/Background.jpg
  Server Frontend/core/src/com/csc480/stats/GUI/StatsScreen.java
Labels: Priority: Low, Type: Maintenance, review

#339 Adjusted board margins and spacing
  Server Backend/static/css/frontend_play_area.css
  Server Backend/views/gameboard.html
Labels: Priority: Low, Type: Bug Fix

#345 Removed useless code
  Server Backend/static/css/frontend_play_area.css
  Server Backend/static/js/frontend_board_model.js
  Server Backend/static/js/frontend_board_view_model.js
Labels: Priority: Low, Type: Maintenance, review

#346 Fixed stats page typo
  Server Frontend/core/src/com/csc480/stats/GUI/Actors/Hud.java
Labels: Priority: Low, Type: Bug Fix, review

#280 Db test update
  Database/Dictionary/src/test/java/com/csc480red/dictionary/DictionaryApplicationTests.java
  Database/GameDB/src/main/java/com/csc480red/gamedb/Player.java
  Database/GameDB/src/main/java/com/csc480red/gamedb/Team.java
  Database/GameDB/src/test/java/com/csc480red/gamedb/GameDbApplicationTests.java
  Database/GameDB/src/test/java/com/csc480red/gamedb/PlayerTest.java
  Database/GameDB/src/test/java/com/csc480red/gamedb/TeamTest.java
Labels: Priority: High, Type: Bug Fix, Type: Enhancement, review

#354 Updated tests with changes from yesterday PR
  Server Frontend/build.gradle
  Server Frontend/core/test/com/csc480/game/Engine/GameManagerTest.java
  Server Frontend/core/test/com/csc480/game/Engine/Model/AITest.java
  Server Frontend/core/test/com/csc480/game/Engine/Model/BoardTest.java
  Server Frontend/core/test/com/csc480/game/Engine/Model/PlayIdeaTest.java
  Server Frontend/core/test/com/csc480/game/Engine/WordVerificationTest.java
  Server Frontend/core/test/com/csc480/game/GUI/Actors/HandActorTest.java
  Server Frontend/core/test/com/csc480/game/GUI/Actors/TileActorTest.java
  Server Frontend/core/test/com/csc480/game/TestRunner.java
Labels: Priority: Low, Type: Maintenance, review

#356 added how to run to README
  README.md
Labels: review
